# Generated by Django 3.0.5 on 2021-01-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nurse',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('registered', models.BooleanField()),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='physician',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='procedure',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trained_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateTimeField(auto_now_add=True)),
                ('certification_expires', models.DateTimeField()),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.physician')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('inuranse_id', models.CharField(max_length=30)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.physician')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.physician')),
            ],
        ),
        migrations.CreateModel(
            name='affliated_with',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_affliated', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.department')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.physician')),
            ],
        ),
    ]
