# Generated by Django 3.0.5 on 2021-01-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('examin_room', models.CharField(max_length=20)),
                ('duty_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.nurse')),
                ('duty_physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.physician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.patient')),
            ],
        ),
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockfloor', models.IntegerField()),
                ('blockcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='medication',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('brand', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(choices=[('genral', 'genral ward'), ('AC', 'Air-Conditioned'), ('Non-AC', 'Non-Air Conditioned')], max_length=25)),
                ('is_available', models.BooleanField()),
                ('blockcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_block_code', to='hospital_admin.block')),
                ('blockfloor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_block_floor', to='hospital_admin.block')),
            ],
        ),
        migrations.CreateModel(
            name='stay',
            fields=[
                ('stay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.room')),
            ],
        ),
        migrations.CreateModel(
            name='undergoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assist_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.physician')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.procedure')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.stay')),
            ],
        ),
        migrations.CreateModel(
            name='prescribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dose', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.appointment')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.physician')),
            ],
        ),
        migrations.CreateModel(
            name='on_call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_call_start', models.DateTimeField(auto_now_add=True)),
                ('on_call_end', models.DateTimeField()),
                ('blockcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_call_block_code', to='hospital_admin.block')),
                ('blockfloor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_call_block_floor', to='hospital_admin.block')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.nurse')),
            ],
        ),
    ]
