# Generated by Django 3.1.5 on 2021-01-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0002_appointment_block_medication_on_call_prescribe_room_stay_undergoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physician',
            old_name='position',
            new_name='spectilization',
        ),
    ]
