# Generated by Django 3.1.5 on 2021-01-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0003_auto_20210120_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='position',
            field=models.CharField(default='physician', max_length=20),
            preserve_default=False,
        ),
    ]
