# Generated by Django 3.1.5 on 2021-01-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0004_physician_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
