# Generated by Django 3.1.5 on 2021-01-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0005_auto_20210121_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='inuranse_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
